Repository BrunosBastos/MedEx, pull requests merged in 2021-06, with the labels that each got.

#15 MED-28: MED-28-backend-allow-products-to-be-added
  backend/.idea/libraries/Maven__org_apache_logging_log4j_log4j_api_2_14_1.xml
  backend/.idea/libraries/Maven__org_junit_jupiter_junit_jupiter_5_7_2.xml
  backend/.idea/libraries/Maven__org_junit_jupiter_junit_jupiter_api_5_7_2.xml
  backend/.idea/libraries/Maven__org_junit_jupiter_junit_jupiter_engine_5_7_2.xml
  backend/.idea/libraries/Maven__org_junit_jupiter_junit_jupiter_params_5_7_2.xml
  backend/.idea/libraries/Maven__org_junit_platform_junit_platform_commons_1_7_2.xml
  backend/.idea/libraries/Maven__org_junit_platform_junit_platform_engine_1_7_2.xml
  backend/.idea/libraries/Maven__org_mockito_mockito_core_3_9_0.xml
  backend/.idea/libraries/Maven__org_mockito_mockito_junit_jupiter_3_9_0.xml
  backend/.idea/libraries/Maven__org_objenesis_objenesis_3_2.xml
  backend/.idea/libraries/Maven__org_ow2_asm_asm_9_1.xml
  backend/.mvn/wrapper/wrapper.iml
  backend/lombok.config
  backend/medex.iml
  backend/pom.xml
  backend/src/main/java/tqs/medex/MedExApplication.java
  backend/src/main/java/tqs/medex/controller/ProductController.java
  backend/src/main/java/tqs/medex/entity/Product.java
  backend/src/main/java/tqs/medex/entity/Supplier.java
  backend/src/main/java/tqs/medex/pojo/ProductPOJO.java
  backend/src/main/java/tqs/medex/repository/ProductRepository.java
  backend/src/main/java/tqs/medex/repository/SupplierRepository.java
  backend/src/main/java/tqs/medex/service/ProductService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/tqs/medex/MedExApplicationTests.java
  backend/src/test/java/tqs/medex/controller/ProductControllerTest.java
  backend/src/test/java/tqs/medex/service/ProductServiceTest.java
  backend/src/test/java/tqs/medex/utils/JsonUtil.java
Labels: enhancement

#25 MED-45: Merge MED-45-fix-return-body-on-authentication to develop
  backend/src/main/java/tqs/medex/controller/AuthController.java
  backend/src/main/java/tqs/medex/entity/User.java
  backend/src/main/java/tqs/medex/pojo/JwtAuthenticationResponse.java
  backend/src/main/java/tqs/medex/service/AuthService.java
  backend/src/test/java/tqs/medex/controller/AuthControllerTest.java
  backend/src/test/java/tqs/medex/service/AuthServiceTest.java
Labels: bug

#27 MED-35:frontend-list-products to develop
  backend/src/test/java/tqs/medex/frontend/ListProductsSteps.java
  backend/src/test/java/tqs/medex/frontend/pages/ListProductsPage.java
  backend/src/test/resources/tqs/medex/frontend/listproducts.feature
  projWebsite/src/components/product/ProductCard.tsx
  projWebsite/src/pages/AddProduct.tsx
  projWebsite/src/pages/ProductList.tsx
  projWebsite/src/pages/ShoppingCart.tsx
  projWebsite/src/services/productService.ts
  projWebsite/src/stores/useShopCartStore.ts
Labels: enhancement

#36 added error messages to auth controller
  backend/src/main/java/tqs/medex/controller/AuthController.java
  backend/src/main/java/tqs/medex/controller/ProductController.java
  backend/src/main/java/tqs/medex/controller/SupplierController.java
  backend/src/main/resources/application.properties
  backend/src/test/java/tqs/medex/controller/AuthControllerIT.java
  backend/src/test/java/tqs/medex/controller/AuthControllerTest.java
  backend/src/test/java/tqs/medex/controller/ProductControllerIT.java
  backend/src/test/java/tqs/medex/controller/ProductControllerTest.java
  backend/src/test/java/tqs/medex/controller/SupplierControllerIT.java
  backend/src/test/java/tqs/medex/controller/SupplierControllerTest.java
  backend/src/test/resources/application.properties
Labels: improvement
